### ISSUE TITLE
GraphqlError: Resource not accessible by integration

### ISSUE THREAD

**Issue by zaibon** [alex-page/add-new-pulls-project#4]
I tried to setup this action on one of my project but I can't seems to be able to make it work.

Here is my worklfow:
```yaml
on: pull_request
name: Add new pull requests to projects
jobs:
  build:
    name: alex-page/add-new-pulls-project
    runs-on: ubuntu-latest
    steps:
    - name: alex-page/add-new-pulls-project
      uses: alex-page/add-new-pulls-project@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '"zero-os_2.0.0 (active)" "In Progress"'
```
And here is the error I get:

```
✖  fatal     GraphqlError: Resource not accessible by integration 
    at /node_modules/@octokit/graphql/lib/graphql.js:31:15
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Toolkit.run.event (/index.js:18:26)
```

The project in which I want to move the PR is actually not on the same repo, but is an organization project. I'm not sure this is actually supported by this actions.
